// ---------------------------------------------------------
// This file was generated by parol.
// Do not edit this file manually.
// Changes will be overwritten on the next build.
// ---------------------------------------------------------

use parol_runtime::{
    ParolError, ParseTree, TokenStream,
    parser::{
        LLKParser, LookaheadDFA, ParseType, Production, Trans, parse_tree_type::TreeConstruct,
    },
};
use scnr2::scanner;
use std::path::Path;

use crate::semantic_triples_grammar::SemanticTriplesGrammar;
use crate::semantic_triples_grammar_trait::SemanticTriplesGrammarAuto;

pub const TERMINAL_NAMES: &[&str; 9] = &[
    /* 0 */ "EndOfInput",
    /* 1 */ "Newline",
    /* 2 */ "Whitespace",
    /* 3 */ "LineComment",
    /* 4 */ "BlockComment",
    /* 5 */ "Id",
    /* 6 */ "MinusMinus",
    /* 7 */ "MinusGT",
    /* 8 */ "Error",
];

scanner! {
    SemanticTriplesGrammarScanner {
        mode INITIAL {
            token r"\r\n|\r|\n" => 1; // "Newline"
            token r"[\s--\r\n]+" => 2; // "Whitespace"
            token r"//.*(\r\n|\r|\n)?" => 3; // "LineComment"
            token r"[a-zA-Z_][a-zA-Z0-9_]*" => 5; // "Id"
            token r"\-\-" => 6; // "MinusMinus"
            token r"\->" => 7; // "MinusGT"
            token r"." => 8; // "Error"
        }
    }
}

const MAX_K: usize = 1;
pub const SKIP_TOKENS_BY_SCANNER_STATE: &[&[parol_runtime::TerminalIndex]; 1] = &[&[]];

pub const NON_TERMINALS: &[&str; 5] = &[
    /* 0 */ "Id",
    /* 1 */ "Predicate",
    /* 2 */ "SemanticTriple",
    /* 3 */ "SemanticTriples",
    /* 4 */ "SemanticTriplesList",
];

pub const LOOKAHEAD_AUTOMATA: &[LookaheadDFA; 5] = &[
    /* 0 - "Id" */
    LookaheadDFA {
        prod0: 4,
        transitions: &[],
        k: 0,
    },
    /* 1 - "Predicate" */
    LookaheadDFA {
        prod0: 5,
        transitions: &[],
        k: 0,
    },
    /* 2 - "SemanticTriple" */
    LookaheadDFA {
        prod0: 3,
        transitions: &[],
        k: 0,
    },
    /* 3 - "SemanticTriples" */
    LookaheadDFA {
        prod0: 0,
        transitions: &[],
        k: 0,
    },
    /* 4 - "SemanticTriplesList" */
    LookaheadDFA {
        prod0: -1,
        transitions: &[Trans(0, 0, 2, 2), Trans(0, 5, 1, 1)],
        k: 1,
    },
];

pub const PRODUCTIONS: &[Production; 6] = &[
    // 0 - SemanticTriples: SemanticTriplesList /* Vec */;
    Production {
        lhs: 3,
        production: &[ParseType::N(4)],
        is_push_production: false,
    },
    // 1 - SemanticTriplesList: SemanticTriple SemanticTriplesList;
    Production {
        lhs: 4,
        production: &[ParseType::N(4), ParseType::N(2)],
        is_push_production: true,
    },
    // 2 - SemanticTriplesList: ;
    Production {
        lhs: 4,
        production: &[],
        is_push_production: false,
    },
    // 3 - SemanticTriple: Id Predicate Id;
    Production {
        lhs: 2,
        production: &[ParseType::N(0), ParseType::N(1), ParseType::N(0)],
        is_push_production: false,
    },
    // 4 - Id: /[a-zA-Z_][a-zA-Z0-9_]*/;
    Production {
        lhs: 0,
        production: &[ParseType::T(5)],
        is_push_production: false,
    },
    // 5 - Predicate: '--'^ /* Clipped */ Id '->'^ /* Clipped */;
    Production {
        lhs: 1,
        production: &[ParseType::T(7), ParseType::N(0), ParseType::T(6)],
        is_push_production: false,
    },
];

pub fn parse<'t, T>(
    input: &'t str,
    file_name: T,
    user_actions: &mut SemanticTriplesGrammar<'t>,
) -> Result<ParseTree, ParolError>
where
    T: AsRef<Path>,
{
    use parol_runtime::{
        parser::{parse_tree_type::SynTree, parser_types::SynTreeFlavor},
        syntree::Builder,
    };
    let mut builder = Builder::<SynTree, SynTreeFlavor>::new_with();
    parse_into(input, &mut builder, file_name, user_actions)?;
    Ok(builder.build()?)
}
#[allow(dead_code)]
pub fn parse_into<'t, T: TreeConstruct<'t>>(
    input: &'t str,
    tree_builder: &mut T,
    file_name: impl AsRef<Path>,
    user_actions: &mut SemanticTriplesGrammar<'t>,
) -> Result<(), ParolError>
where
    ParolError: From<T::Error>,
{
    use semantic_triples_grammar_scanner::SemanticTriplesGrammarScanner;
    let mut llk_parser = LLKParser::new(
        3,
        LOOKAHEAD_AUTOMATA,
        PRODUCTIONS,
        TERMINAL_NAMES,
        NON_TERMINALS,
    );
    llk_parser.trim_parse_tree();
    let scanner = SemanticTriplesGrammarScanner::new();
    // Initialize wrapper
    let mut user_actions = SemanticTriplesGrammarAuto::new(user_actions);
    llk_parser.parse_into(
        tree_builder,
        TokenStream::new_with_skip_tokens(
            input,
            file_name,
            scanner.scanner_impl.clone(),
            &SemanticTriplesGrammarScanner::match_function,
            MAX_K,
            SKIP_TOKENS_BY_SCANNER_STATE,
        )
        .unwrap(),
        &mut user_actions,
    )
}
